//! iOS FFI bridge — C-compatible functions callable from Swift.
//!
//! Uses simple C types (null-terminated char pointers, integers) to
//! cross the Rust↔Swift boundary. Swift code calls these via a
//! bridging header generated by cbindgen.

use std::ffi::{CStr, CString};
use std::net::TcpListener;
use std::os::raw::c_char;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::Mutex;
use std::thread::JoinHandle;
use std::time::{Duration, SystemTime};

use serde::{Deserialize, Serialize};

use crate::{LocalIdentity, PairingInvitation, PairingSession, TrustStore};

// ── JSON interchange / listener state ──────────────────────────────

#[derive(Serialize, Deserialize)]
struct IosIdentity {
    device_id: String,
    device_name: String,
    fingerprint: String,
    public_key: String,
    dh_public_key: String,
    signing_key_hex: String,
    static_dh_key_hex: String,
    created_at_secs: u64,
}

#[derive(Serialize)]
struct IosSendResult {
    success: bool,
    detail: String,
}

#[derive(Serialize)]
struct IosListenerStatus {
    running: bool,
    detail: String,
    error: String,
}

static LISTENER_RUNNING: AtomicBool = AtomicBool::new(false);
static LISTENER_LAST_ERROR: Mutex<Option<String>> = Mutex::new(None);
static LISTENER_EPOCH: AtomicU64 = AtomicU64::new(0);
static LISTENER_HANDLE: Mutex<Option<JoinHandle<()>>> = Mutex::new(None);

// ── Helpers ────────────────────────────────────────────────────────

unsafe fn c_str_to_string(ptr: *const c_char) -> String {
    if ptr.is_null() {
        return String::new();
    }
    CStr::from_ptr(ptr).to_string_lossy().into_owned()
}

fn string_to_c(s: &str) -> *mut c_char {
    CString::new(s).unwrap_or_default().into_raw()
}

fn free_c_string(ptr: *mut c_char) {
    if !ptr.is_null() {
        unsafe {
            drop(CString::from_raw(ptr));
        }
    }
}

fn ok_json<T: Serialize>(value: &T) -> String {
    serde_json::to_string(value).unwrap_or_default()
}

fn err_json(message: &str) -> String {
    format!(r#"{{"error":"{}"}}"#, message.replace('"', "'"))
}

fn hex_to_array<const N: usize>(hex: &str, label: &str) -> Result<[u8; N], String> {
    let bytes = crate::decode_hex(hex).map_err(|e| format!("{label}: {e}"))?;
    bytes
        .try_into()
        .map_err(|_| format!("{label} must be {N} bytes"))
}

fn to_local_identity(identity: &IosIdentity) -> Result<LocalIdentity, String> {
    let signing_key = hex_to_array(&identity.signing_key_hex, "signing_key")?;
    let static_dh_key = hex_to_array(&identity.static_dh_key_hex, "static_dh_key")?;
    let created_at = std::time::UNIX_EPOCH + Duration::from_secs(identity.created_at_secs);
    Ok(LocalIdentity::from_keys(
        &identity.device_name,
        signing_key,
        static_dh_key,
        created_at,
    ))
}

fn set_listener_last_error(error: Option<String>) {
    if let Ok(mut last_error) = LISTENER_LAST_ERROR.lock() {
        *last_error = error;
    }
}

fn listener_last_error() -> String {
    LISTENER_LAST_ERROR
        .lock()
        .ok()
        .and_then(|last_error| last_error.clone())
        .unwrap_or_default()
}

fn listener_status_json() -> String {
    let running = LISTENER_RUNNING.load(Ordering::Relaxed);
    let error = listener_last_error();
    let detail = if running {
        "listener running"
    } else if error.is_empty() {
        "listener stopped"
    } else {
        "listener failed"
    };
    ok_json(&IosListenerStatus {
        running,
        detail: detail.to_string(),
        error,
    })
}

fn stop_and_join_listener() {
    LISTENER_RUNNING.store(false, Ordering::SeqCst);
    let handle = LISTENER_HANDLE.lock().ok().and_then(|mut slot| slot.take());
    if let Some(handle) = handle {
        let _ = handle.join();
    }
}

// ── Identity ───────────────────────────────────────────────────────

#[no_mangle]
pub extern "C" fn linkhub_generate_identity(device_name: *const c_char) -> *mut c_char {
    let name = unsafe { c_str_to_string(device_name) };
    let identity = LocalIdentity::generate(&name, SystemTime::now());
    let json = serde_json::json!({
        "device_id": identity.device_id(),
        "device_name": identity.device_name(),
        "fingerprint": identity.identity().fingerprint(),
        "public_key": identity.public_key(),
        "dh_public_key": identity.dh_public_key(),
        "signing_key_hex": identity.signing_key_hex(),
        "static_dh_key_hex": identity.static_dh_key_hex(),
        "created_at_secs": identity.created_at()
            .duration_since(std::time::UNIX_EPOCH).unwrap_or_default().as_secs(),
    })
    .to_string();
    string_to_c(&json)
}

#[no_mangle]
pub extern "C" fn linkhub_restore_identity(
    signing_key_hex: *const c_char,
    static_dh_key_hex: *const c_char,
    device_name: *const c_char,
) -> *mut c_char {
    let result = (|| -> Result<String, String> {
        let sk = unsafe { c_str_to_string(signing_key_hex) };
        let dh = unsafe { c_str_to_string(static_dh_key_hex) };
        let name = unsafe { c_str_to_string(device_name) };
        let sk_bytes = crate::decode_hex(&sk).map_err(|e| format!("{e}"))?;
        let dh_bytes = crate::decode_hex(&dh).map_err(|e| format!("{e}"))?;
        let sk: [u8; 32] = sk_bytes.try_into().map_err(|_| "key len".to_string())?;
        let dh: [u8; 32] = dh_bytes.try_into().map_err(|_| "key len".to_string())?;
        let id = LocalIdentity::from_keys(&name, sk, dh, SystemTime::now());
        Ok(serde_json::json!({"device_id": id.device_id(), "fingerprint": id.identity().fingerprint()}).to_string())
    })();
    match result {
        Ok(json) => string_to_c(&json),
        Err(e) => string_to_c(&format!(r#"{{"error":"{}"}}"#, e)),
    }
}

// ── Pairing ────────────────────────────────────────────────────────

#[no_mangle]
pub extern "C" fn linkhub_generate_pairing_payload(
    device_id: *const c_char,
    device_name: *const c_char,
    public_key: *const c_char,
    dh_public_key: *const c_char,
    ttl_seconds: u64,
) -> *mut c_char {
    let identity = crate::DeviceIdentity::new(
        unsafe { c_str_to_string(device_id) },
        unsafe { c_str_to_string(device_name) },
        unsafe { c_str_to_string(public_key) },
        unsafe { c_str_to_string(dh_public_key) },
    );
    let invitation = PairingInvitation::new(
        identity,
        SystemTime::now(),
        Duration::from_secs(ttl_seconds),
    );
    string_to_c(&invitation.to_payload())
}

#[no_mangle]
pub extern "C" fn linkhub_parse_pairing_payload(
    identity_json: *const c_char,
    payload: *const c_char,
) -> *mut c_char {
    let json = unsafe { c_str_to_string(identity_json) };
    let payload = unsafe { c_str_to_string(payload) };
    let result = (|| -> Result<String, String> {
        let jni: serde_json::Value = serde_json::from_str(&json).map_err(|e| format!("{e}"))?;
        let did = jni["device_id"].as_str().unwrap_or("");
        let dname = jni["device_name"].as_str().unwrap_or("");
        let pk = jni["public_key"].as_str().unwrap_or("");
        let dh = jni["dh_public_key"].as_str().unwrap_or("");
        let local = crate::DeviceIdentity::new(did, dname, pk, dh);
        let invitation = PairingInvitation::from_payload(&payload, SystemTime::now())
            .map_err(|e| format!("{e}"))?;
        let session = PairingSession::new(local, invitation);
        Ok(serde_json::json!({
            "peer_device_id": session.peer_identity().device_id(),
            "peer_device_name": session.peer_identity().device_name(),
            "fingerprint": session.peer_identity().fingerprint(),
            "confirmation_code": session.confirmation_code(),
        })
        .to_string())
    })();
    match result {
        Ok(s) => string_to_c(&s),
        Err(e) => string_to_c(&format!(r#"{{"error":"{}"}}"#, e)),
    }
}

#[no_mangle]
pub extern "C" fn linkhub_confirm_pairing(
    identity_json: *const c_char,
    payload: *const c_char,
    confirmation_code: *const c_char,
) -> *mut c_char {
    let json = unsafe { c_str_to_string(identity_json) };
    let payload = unsafe { c_str_to_string(payload) };
    let code = unsafe { c_str_to_string(confirmation_code) };
    let result = (|| -> Result<String, String> {
        let jni: serde_json::Value = serde_json::from_str(&json).map_err(|e| format!("{e}"))?;
        let did = jni["device_id"].as_str().unwrap_or("");
        let dname = jni["device_name"].as_str().unwrap_or("");
        let pk = jni["public_key"].as_str().unwrap_or("");
        let dh = jni["dh_public_key"].as_str().unwrap_or("");
        let local = crate::DeviceIdentity::new(did, dname, pk, dh);
        let invitation = PairingInvitation::from_payload(&payload, SystemTime::now())
            .map_err(|e| format!("{e}"))?;
        let session = PairingSession::new(local, invitation);
        let trusted = session
            .confirm(&code, SystemTime::now(), SystemTime::now())
            .map_err(|e| format!("{e}"))?;
        Ok(serde_json::json!({
            "success": true,
            "device_id": trusted.device_id(),
            "device_name": trusted.device_name(),
            "fingerprint": trusted.fingerprint(),
        })
        .to_string())
    })();
    match result {
        Ok(s) => string_to_c(&s),
        Err(e) => string_to_c(&format!(r#"{{"success":false,"error":"{}"}}"#, e)),
    }
}

// ── Local-network send/listen ──────────────────────────────────────

#[no_mangle]
pub extern "C" fn linkhub_send_text(
    identity_json: *const c_char,
    peer_addr: *const c_char,
    peer_device_id: *const c_char,
    peer_dh_hex: *const c_char,
    text: *const c_char,
) -> *mut c_char {
    let result = (|| -> Result<String, String> {
        let json = unsafe { c_str_to_string(identity_json) };
        let addr = unsafe { c_str_to_string(peer_addr) };
        let peer_id = unsafe { c_str_to_string(peer_device_id) };
        let dh_hex = unsafe { c_str_to_string(peer_dh_hex) };
        let text = unsafe { c_str_to_string(text) };
        let identity: IosIdentity = serde_json::from_str(&json).map_err(|e| format!("{e}"))?;
        let local = to_local_identity(&identity)?;
        let dh_bytes = hex_to_array(&dh_hex, "dh_key")?;
        crate::run_authenticated_text_sender(&addr, local, &peer_id, &dh_bytes, &text)
            .map_err(|e| format!("send failed: {e}"))?;
        Ok(ok_json(&IosSendResult {
            success: true,
            detail: "text sent".to_string(),
        }))
    })();
    match result {
        Ok(json) => string_to_c(&json),
        Err(error) => string_to_c(&err_json(&error)),
    }
}

#[no_mangle]
pub extern "C" fn linkhub_send_file(
    identity_json: *const c_char,
    peer_addr: *const c_char,
    peer_device_id: *const c_char,
    peer_dh_hex: *const c_char,
    file_path: *const c_char,
) -> *mut c_char {
    let result = (|| -> Result<String, String> {
        let json = unsafe { c_str_to_string(identity_json) };
        let addr = unsafe { c_str_to_string(peer_addr) };
        let peer_id = unsafe { c_str_to_string(peer_device_id) };
        let dh_hex = unsafe { c_str_to_string(peer_dh_hex) };
        let path = unsafe { c_str_to_string(file_path) };
        let identity: IosIdentity = serde_json::from_str(&json).map_err(|e| format!("{e}"))?;
        let local = to_local_identity(&identity)?;
        let dh_bytes = hex_to_array(&dh_hex, "dh_key")?;
        crate::run_authenticated_file_sender(&addr, local, &peer_id, &dh_bytes, &path)
            .map_err(|e| format!("send failed: {e}"))?;
        Ok(ok_json(&IosSendResult {
            success: true,
            detail: "file sent".to_string(),
        }))
    })();
    match result {
        Ok(json) => string_to_c(&json),
        Err(error) => string_to_c(&err_json(&error)),
    }
}

#[no_mangle]
pub extern "C" fn linkhub_start_listener(
    identity_json: *const c_char,
    bind_addr: *const c_char,
    trust_store_path: *const c_char,
    receive_dir: *const c_char,
) -> *mut c_char {
    let result = (|| -> Result<String, String> {
        if LISTENER_RUNNING.load(Ordering::SeqCst) {
            return Ok(listener_status_json());
        }
        stop_and_join_listener();

        let json = unsafe { c_str_to_string(identity_json) };
        let addr = unsafe { c_str_to_string(bind_addr) };
        let trust_store_path = unsafe { c_str_to_string(trust_store_path) };
        let receive_dir = unsafe { c_str_to_string(receive_dir) };
        let identity: IosIdentity = serde_json::from_str(&json).map_err(|e| format!("{e}"))?;
        let local = to_local_identity(&identity)?;
        let trust_store =
            TrustStore::load_from_path(&trust_store_path).map_err(|e| format!("{e}"))?;
        let listener = TcpListener::bind(&addr)
            .map_err(|e| format!("failed to bind listener on {addr}: {e}"))?;

        set_listener_last_error(None);
        let my_epoch = LISTENER_EPOCH.fetch_add(1, Ordering::SeqCst) + 1;
        LISTENER_RUNNING.store(true, Ordering::SeqCst);
        let handle = std::thread::spawn(move || {
            let outcome = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                crate::run_authenticated_listener_on(
                    listener,
                    &addr,
                    local,
                    trust_store,
                    &receive_dir,
                    || !LISTENER_RUNNING.load(Ordering::Relaxed),
                )
            }));
            match outcome {
                Ok(Ok(())) => {}
                Ok(Err(error)) => set_listener_last_error(Some(format!("{error}"))),
                Err(panic) => {
                    let message = panic
                        .downcast_ref::<&str>()
                        .map(|s| s.to_string())
                        .or_else(|| panic.downcast_ref::<String>().cloned())
                        .unwrap_or_else(|| "listener thread panicked".to_string());
                    set_listener_last_error(Some(format!("listener panicked: {message}")));
                }
            }
            if LISTENER_EPOCH.load(Ordering::SeqCst) == my_epoch {
                LISTENER_RUNNING.store(false, Ordering::SeqCst);
            }
        });
        if let Ok(mut slot) = LISTENER_HANDLE.lock() {
            *slot = Some(handle);
        }
        Ok(listener_status_json())
    })();
    match result {
        Ok(json) => string_to_c(&json),
        Err(error) => string_to_c(&err_json(&error)),
    }
}

#[no_mangle]
pub extern "C" fn linkhub_stop_listener() -> *mut c_char {
    stop_and_join_listener();
    string_to_c(&listener_status_json())
}

#[no_mangle]
pub extern "C" fn linkhub_listener_status() -> *mut c_char {
    string_to_c(&listener_status_json())
}

// ── Cleanup ────────────────────────────────────────────────────────

#[no_mangle]
pub extern "C" fn linkhub_free_string(ptr: *mut c_char) {
    free_c_string(ptr);
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::CString;

    #[test]
    fn c_string_round_trip() {
        let original = CString::new("hello world").unwrap();
        let ptr = original.into_raw();
        let result = unsafe { c_str_to_string(ptr) };
        assert_eq!(result, "hello world");
        free_c_string(ptr);
    }
}
