//! iOS FFI bridge — C-compatible functions callable from Swift.
//!
//! Uses simple C types (null-terminated char pointers, integers) to
//! cross the Rust↔Swift boundary. Swift code calls these via a
//! bridging header generated by cbindgen.

use std::ffi::{CStr, CString};
use std::os::raw::c_char;
use std::time::{Duration, Instant, SystemTime};

use crate::{new_pairing_nonce, LocalIdentity, PairingInvitation, PairingSession};

// ── Helpers ────────────────────────────────────────────────────────

unsafe fn c_str_to_string(ptr: *const c_char) -> String {
    if ptr.is_null() {
        return String::new();
    }
    CStr::from_ptr(ptr).to_string_lossy().into_owned()
}

fn string_to_c(s: &str) -> *mut c_char {
    CString::new(s).unwrap_or_default().into_raw()
}

fn free_c_string(ptr: *mut c_char) {
    if !ptr.is_null() {
        unsafe {
            drop(CString::from_raw(ptr));
        }
    }
}

// ── Identity ───────────────────────────────────────────────────────

#[no_mangle]
pub extern "C" fn linkhub_generate_identity(device_name: *const c_char) -> *mut c_char {
    let name = unsafe { c_str_to_string(device_name) };
    let identity = LocalIdentity::generate(&name, SystemTime::now());
    let json = serde_json::json!({
        "device_id": identity.device_id(),
        "device_name": identity.device_name(),
        "fingerprint": identity.identity().fingerprint(),
        "public_key": identity.public_key(),
        "dh_public_key": identity.dh_public_key(),
        "signing_key_hex": identity.signing_key_hex(),
        "static_dh_key_hex": identity.static_dh_key_hex(),
        "created_at_secs": identity.created_at()
            .duration_since(std::time::UNIX_EPOCH).unwrap_or_default().as_secs(),
    })
    .to_string();
    string_to_c(&json)
}

#[no_mangle]
pub extern "C" fn linkhub_restore_identity(
    signing_key_hex: *const c_char,
    static_dh_key_hex: *const c_char,
    device_name: *const c_char,
) -> *mut c_char {
    let result = (|| -> Result<String, String> {
        let sk = unsafe { c_str_to_string(signing_key_hex) };
        let dh = unsafe { c_str_to_string(static_dh_key_hex) };
        let name = unsafe { c_str_to_string(device_name) };
        let sk_bytes = crate::decode_hex(&sk).map_err(|e| format!("{e}"))?;
        let dh_bytes = crate::decode_hex(&dh).map_err(|e| format!("{e}"))?;
        let sk: [u8; 32] = sk_bytes.try_into().map_err(|_| "key len".to_string())?;
        let dh: [u8; 32] = dh_bytes.try_into().map_err(|_| "key len".to_string())?;
        let id = LocalIdentity::from_keys(&name, sk, dh, SystemTime::now());
        Ok(serde_json::json!({"device_id": id.device_id(), "fingerprint": id.identity().fingerprint()}).to_string())
    })();
    match result {
        Ok(json) => string_to_c(&json),
        Err(e) => string_to_c(&format!(r#"{{"error":"{}"}}"#, e)),
    }
}

// ── Pairing ────────────────────────────────────────────────────────

#[no_mangle]
pub extern "C" fn linkhub_generate_pairing_payload(
    device_id: *const c_char,
    device_name: *const c_char,
    public_key: *const c_char,
    dh_public_key: *const c_char,
    ttl_seconds: u64,
) -> *mut c_char {
    let identity = crate::DeviceIdentity::new(
        unsafe { c_str_to_string(device_id) },
        unsafe { c_str_to_string(device_name) },
        unsafe { c_str_to_string(public_key) },
        unsafe { c_str_to_string(dh_public_key) },
    );
    let invitation = PairingInvitation::new(
        identity,
        new_pairing_nonce(),
        Instant::now(),
        Duration::from_secs(ttl_seconds),
    );
    string_to_c(&invitation.to_payload())
}

#[no_mangle]
pub extern "C" fn linkhub_parse_pairing_payload(
    identity_json: *const c_char,
    payload: *const c_char,
) -> *mut c_char {
    let json = unsafe { c_str_to_string(identity_json) };
    let payload = unsafe { c_str_to_string(payload) };
    let result = (|| -> Result<String, String> {
        let jni: serde_json::Value = serde_json::from_str(&json).map_err(|e| format!("{e}"))?;
        let did = jni["device_id"].as_str().unwrap_or("");
        let dname = jni["device_name"].as_str().unwrap_or("");
        let pk = jni["public_key"].as_str().unwrap_or("");
        let dh = jni["dh_public_key"].as_str().unwrap_or("");
        let local = crate::DeviceIdentity::new(did, dname, pk, dh);
        let invitation = PairingInvitation::from_payload(&payload, Instant::now())
            .map_err(|e| format!("{e}"))?;
        let session = PairingSession::new(local, invitation);
        Ok(serde_json::json!({
            "peer_device_id": session.peer_identity().device_id(),
            "peer_device_name": session.peer_identity().device_name(),
            "fingerprint": session.peer_identity().fingerprint(),
            "confirmation_code": session.confirmation_code(),
        })
        .to_string())
    })();
    match result {
        Ok(s) => string_to_c(&s),
        Err(e) => string_to_c(&format!(r#"{{"error":"{}"}}"#, e)),
    }
}

#[no_mangle]
pub extern "C" fn linkhub_confirm_pairing(
    identity_json: *const c_char,
    payload: *const c_char,
    confirmation_code: *const c_char,
) -> *mut c_char {
    let json = unsafe { c_str_to_string(identity_json) };
    let payload = unsafe { c_str_to_string(payload) };
    let code = unsafe { c_str_to_string(confirmation_code) };
    let result = (|| -> Result<String, String> {
        let jni: serde_json::Value = serde_json::from_str(&json).map_err(|e| format!("{e}"))?;
        let did = jni["device_id"].as_str().unwrap_or("");
        let dname = jni["device_name"].as_str().unwrap_or("");
        let pk = jni["public_key"].as_str().unwrap_or("");
        let dh = jni["dh_public_key"].as_str().unwrap_or("");
        let local = crate::DeviceIdentity::new(did, dname, pk, dh);
        let invitation = PairingInvitation::from_payload(&payload, Instant::now())
            .map_err(|e| format!("{e}"))?;
        let session = PairingSession::new(local, invitation);
        let trusted = session
            .confirm(&code, Instant::now(), SystemTime::now())
            .map_err(|e| format!("{e}"))?;
        Ok(serde_json::json!({
            "success": true,
            "device_id": trusted.device_id(),
            "device_name": trusted.device_name(),
            "fingerprint": trusted.fingerprint(),
        })
        .to_string())
    })();
    match result {
        Ok(s) => string_to_c(&s),
        Err(e) => string_to_c(&format!(r#"{{"success":false,"error":"{}"}}"#, e)),
    }
}

// ── Cleanup ────────────────────────────────────────────────────────

#[no_mangle]
pub extern "C" fn linkhub_free_string(ptr: *mut c_char) {
    free_c_string(ptr);
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::CString;

    #[test]
    fn c_string_round_trip() {
        let original = CString::new("hello world").unwrap();
        let ptr = original.into_raw();
        let result = unsafe { c_str_to_string(ptr) };
        assert_eq!(result, "hello world");
        free_c_string(ptr);
    }
}
